@startuml Diagrama Contenedor
title Diagrama contenedor del servidor echo

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

System_Ext(usuario, "Usuario", "Usuario que inicia el servidor echo")

Boundary(servidor_echo, "Servidor echo") {

  Component(start, "start", "Inicia el servidor echo")
  Component(creation, "creation", "Crea el/los mensaje/s")
  Component(action, "action", "Opera con el/los mensaje/s")
  Component(print, "print", "Imprime el/los mensaje/s")

}

Rel(usuario, start, "Inicio servidor echo", "n")
Rel(start, creation, "Envia", "Manda la instrucción de crear el/los mensaje/s")
Rel(creation, action, "Envía", "Mensaje a operar")
Rel(action, print, "Envía", "Resultado de la operación")
Rel(print, output, "IO.puts", "Último mensaje")

SHOW_FLOATING_LEGEND()
@enduml